'project_id_env': CROWDIN_PROJECT_ID
'api_token_env': CROWDIN_PERSONAL_TOKEN
"base_path": "packages/tx-categorize/src"

"preserve_hierarchy": true

files: [
  {
    "source": "/localization/locales/en/translation.json",
    "translation": "/localization/locales/%two_letters_code%/translation.json",
  }
]