export enum ChainId {
  ETHEREUM = 1,
  POLYGON = 137,
  BSC = 56,
  ARBITRUM = 42161,
  OPTIMISM = 10,
  AVALANCHE = 43114,
  FANTOM = 250,
  CELO = 42220,
  CRONOS = 25,
  AURORA = 1313161554,
  MOONBEAM = 1284,
  MOONRIVER = 1285,
  BASE = 8453,
  LINEA = 59144,
}

export const NETWORKS_CONFIG: Record<number, boolean> = {
  [ChainId.ETHEREUM]: true,
  [ChainId.POLYGON]: true,
  [ChainId.BSC]: true,
  [ChainId.ARBITRUM]: true,
  [ChainId.OPTIMISM]: true,
  [ChainId.AVALANCHE]: true,
  [ChainId.FANTOM]: true,
  [ChainId.CELO]: true,
  [ChainId.CRONOS]: true,
  [ChainId.AURORA]: true,
  [ChainId.MOONBEAM]: true,
  [ChainId.MOONRIVER]: true,
  [ChainId.BASE]: true,
  [ChainId.LINEA]: true,
}
