name: Publish

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    strategy:
      matrix:
        node-version: [ 20.x ]
    uses: consensys-vertical-apps/shared-services-workflows/.github/workflows/js-publish-npm.yml@v0.54.0
    with:
      environment: prd
      node_version: ${{ matrix.node-version }}
      npm_client: yarn
      yarn_version: 4
