name: Test

on:
  workflow_call:
    secrets:
      INFURA_API_KEY:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node Base actions
        uses: consensys-vertical-apps/shared-services-workflows/.github/actions/node-base-actions@v0.54.0
        with:
          node_version: ${{ matrix.node-version }}
          npm_client: yarn
          yarn_version: 4

      - name: Building packages
        run: yarn build

      - name: Run tests
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        run: yarn test
